
---


---
####Discussion, Implications and Limitations:  

There are certain limitations of this research analysis. Perhaps, the most important one is that this data is self-reported and is therefore vulnerable to participant bias. The amounts reported in the survey can be over stated, understated or misreported by the participant. Some demographic groups may be more prone to overstate or understate their saving levels due to psychological, social or cultural reasons. The data does not distinguish between the type of savings (pensions, interest, stocks, etc) and therefore this analysis cannot be useful to draw conclusions about various saving schemes either.  

Another limitation is that when race is introduced to the model, the sample falls from roughly 50,000 to 1,200, which can affect the data. However, this opens up avenues for future research to study saving perceptions and saving behaviors of racial minorities to check whether similar results emerge when sample size is increased.  

For future research in this field, there is room to analyze interactions between gender and race, income and race or even age categories and race to study whether the effects of these interactions are significant or not. In this paper, no interactions have been included so a more complex and in-depth analysis is not possible.  

What is also interesting and has potential for further research is the difference in frequency of saving behavior and nominal saving amounts. If in fact, South Asians are saving less frequently than Whites but are saving larger amounts, this has implications for government saving schemes, private saving schemes and even programs on financial literacy for racial minorities. By understanding trends in saving behaviors and self-perceptions of savings, policy makers, banks and saving institutions can create programs that cater to the specific needs of less-privileged demographic groups like women, racial minorities and immigrants.  

Recommendations for improving this analysis include removing outliers from the dataset that can overstate or understate the mean income and amount saved, including more explanatory variables to increase the R2 of the model and testing the multicollinearity of the explanatory variables.   


####Conclusion:
I set out to find differences in saving behaviors between whites and racial minorities in the UK. What I found was that after holding gender, income and age constant, South Asians were saving more than Whites per month. However, they were less likely to save frequently than Whites.  

