---




---

####Literature Review

Saving behavior has been looked at closely by several economists, sociologists and anthropologists in various contexts. This line of work has shown that age (Bassett, Fleming & Rodrigues, 1998), income (Bassett et al., 1998; Grable & Lytton, 1997), educational level (DeVaney & Su, 1997), marital status (Henkens, 1999), and gender (Behling, Kilty & Foster, 1983) are all systematically related to saving practices.  

Employment rates and pay levels are variables that have an important effect on the receipt of sufficient pension benefits once in retirement. Individuals from racial minority groups, particularly of Pakistani and Bangladeshi origins, are, on average, less likely to be in employment, and more likely to be in low paid jobs and self-employment than the white majority, which implies they have lower incomes (Berthoud, 2000), which can explain their lower saving levels.

Gender also is an important factor in saving behaviors of ethnic minorities. One of Ginn and Arber’s (2001) most relevant findings is that ethnicity and gender are both important factors in explaining private pension coverage. They show that Pakistani and Bangladeshi women are at a significant disadvantage in terms of employment status. The difficulties experienced during their working lives contribute to the disadvantage that racial minorities experience in terms of participation in good value occupational pension schemes (Gough, Adami, 2012).  

There is also a difference within the older and younger generation in racial minorities. In Asian households, the older generation was more inclined towards expecting assistance and relying on help from extended family and children. The younger generation is moving towards a more self-sufficient life style (Gough and Hicks, 2009). Similarly, in Pakistani households, the younger generation is moving away from pension schemes and more inclined towards investing in businesses (Nesbitt and Neary, 2001). This has implications for saving behavior because if younger Asians are becoming self-sufficient, they have a higher need to save and if Pakistani young individuals are moving away from pensions and businesses, their saving trends and frequencies will be affected. 
