---



---
####Methodology:

There are two dependent variables for my analysis; the first is the actual amount saved by an individual per month and the second is whether the individual saves regularly or not. The actual amount saved by an individual per month is recorded as a lump sum amount in pounds, not as percentage of income. This amount does not specify how this amount is saved; whether it is from a certain investment or not, it is the total amount saved by the individual in a month. It is also a self-reported amount. This variable is transformed because the distribution of this variable is not normal. I transformed this variable by taking the natural log of the amount saved monthly, which made the distribution appear relatively normal (Graph 1).     

The second dependent variable measures regularity of saving. This variable initially had 4 categories (“on a regular basis” and “from time to time”, “I don’t know” and “other”). This variable was recoded to contain a binary (“saves regularly” for people who save on a regular basis and “saves time to timer” for people that save from time to time). The other two categories were merged with the null values because of the insignificant number of individuals in each category. Since this is a categorical dependent variable, I conducted a Wald-Chi2 test (appendix 3). The results show that we can reject the null hypothesis that the variables age, age2, logincome and race have no effect on the dependent variable. However, the chi2 result for gender shows that gender can be excluded from the model. However, despite the result, I shall include gender in the model because the literature suggests that gender has a significant relationship with saving levels.  

My independent variables include gender, logincome, age, age*age, and ethnicity.     

Income has been transformed into a log variable to “normalize” the distribution (Graph 2). As for ethnicity, Graph 3 represents the distribution of ethnicities in the sample. This is fairly representative of the distribution of racial minorities in the UK population (Ethnicity and Religion Statistics). Whites make up a large percentage in the UK, with blacks and Asians and South Asians as racial minorities. Race has been recoded into 4 major categories, Whites, mixed races, South Asians and other (Asians, Blacks, Arabs, other minorities).    

Age has been transformed to age*age to account for a non-linear effect mentioned in the literature. Modigliani and Brumberg (1954) stated that within their framework the effect of age composition on saving is nonlinear and varies with income growth.    

While these models are not ideal and have limitations, considering the scope of the research and the available dataset, I have chosen the above-mentioned regression techniques and models. Any limitations are discussed further in the paper. The descriptive statistics of the dependent and independent variables can be viewed in Appendix 1.  

I will report results for two regressions; Regression A is an OLS multivariate regression with logamountsaved (monthly amount saved) as the dependent variable and Regression B is a multivariate logistic regression with “regsave” (frequency of saving) as the dependent variable. Both regressions have a 95% confidence level.    
