---



---
####Results:
This section is divided into two parts: Results of Regression A, Results of Regression B. The regression results are available in Appendix 2.  

#####Regression A:
The results of the regression show that South Asians in the UK save 28% more than whites in the UK. The results also show that there is no significant difference between the saving levels of women and men in the UK, and that as incomes increase so do saving levels.  

There is little literature supporting the results that minorities in the UK are saving more on average than whites because of income levels and access to financial opportunities. However, since income is controlled for, this can be indicative of South Asian saving behaviors. Again, there is little literature to support these claims but South Asian saving behavior can be attributed to motivations linked to saving for their children’s weddings and for bequests to their children and grandchildren. Studies show that minorities are less likely to buy insurance (Saver, Doescher, 2000), therefore they may be saving more for precautionary purposes.   

The difference in mean levels of income for whites and South Asians is not that pronounced (Graph 4). This can be tested using a comparison of means test to check whether the difference in means is significant. In Graph 5, however, we can see that South Asians in the sample are saving more than Whites on average. Perhaps, the income disparities in this sample are not representative of the income disparities in the population or other samples. These results should be taken with a pinch of salt because these are self-reported amounts, that can be easily over and understated. There are also outliers in the sample that may be contributing to these results. 

#####Regression B:

Income has a significant relationship with regularity of saving. People with higher levels of income are more likely to report that they save more regularly. What is interesting though is that while South Asians saved more than Whites in nominal terms, they were less likely to report that they save regularly than Whites. As for other minorities, the results were not significant. This difference between nominal saving amounts and regularity of saving can be attributed to multiple reasons. One of them is that perhaps South Asians are saving larger amounts but are not saving as regularly as Whites and perhaps Whites may be saving smaller amounts but more regularly. This can also be because of some cultural, psychological or social reasons that make South Asians feel like they are not saving regularly enough and perceive themselves to be saving less regularly. This could be because of their economic disadvantage and need to save more that motivates them to save larger amounts in nominal terms but perceive themselves to be saving less regularly.Furthermore, regularity of savings can be associated with having a secure job. Literature in the introduction suggests that South Asians and minorities in the UK are more likely to hold odd jobs and not have a regular stream of income or be unemployed. This can perhaps explain why South Asians are not saving as regularly as Whites, therefore when they have an opportunity to save, they save larger amounts. Having said that, this result also has its limitations because the word "regular" can mean different things to different people. People can perceive the word "regular" differently and can give their response according to their perception. 
